# Generated by Django 5.2.15 on 2026-06-27 10:45

import apps.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cdr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src_number",
                    models.CharField(
                        db_index=True,
                        max_length=11,
                        validators=[apps.core.validators.PhoneNumberMobileValidator()],
                        verbose_name="Source phone number",
                    ),
                ),
                (
                    "dest_number",
                    models.CharField(
                        db_index=True,
                        max_length=11,
                        validators=[apps.core.validators.PhoneNumberMobileValidator()],
                        verbose_name="Destination phone number",
                    ),
                ),
                (
                    "call_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of the call in seconds",
                        null=True,
                        validators=[apps.core.validators.CallDuration()],
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("call_successful", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Call Detail Record",
                "verbose_name_plural": "Call Detail Records",
                "indexes": [
                    models.Index(
                        fields=["src_number", "dest_number", "timestamp"],
                        name="cdr_cdr_src_num_2ee275_idx",
                    )
                ],
            },
        ),
    ]
